# Generated by Django 3.0 on 2021-06-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paln_name', models.CharField(max_length=50)),
                ('year_of_warrenty', models.PositiveIntegerField(default=1)),
                ('finance_plan', models.CharField(default='Unavailable', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=80)),
                ('car_model', models.CharField(max_length=100)),
                ('production_year', models.CharField(max_length=40)),
                ('car_body', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=50)),
                ('car_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carInfo.CarPlan')),
            ],
        ),
    ]
